upstream app_image {
  server 127.0.0.1:8080;
  keepalive 64;
  keepalive_requests 10000;
}

upstream app_web {
  server 127.0.0.1:8080;
  keepalive 64;
  keepalive_requests 10000;
}

server {
  listen 80 default_server;
  listen [::]:80 default_server;

  client_max_body_size 10m;
  root /home/isucon/private_isu/webapp/public/;

  location ~ ^/(js|css|img)/ {
    expires 1d;
    access_log off;
    open_file_cache max=1024 inactive=60s;
  }

  location = /favicon.ico {
    expires 1d;
    access_log off;
    log_not_found off;
  }

  location ~ ^/image/(\d+)\.(jpg|png|gif)$ {
    expires 1d;
    try_files /image/$1.$2 @app_image;
  }

  location @app_image {
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_pass http://app_image;
  }

  location / {
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_pass http://app_web;
  }
}
